name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get bun version from package.json
        id: bun-version
        shell: bash
        run: echo "bun_version=$(node -p 'require(`./package.json`).engines.bun')" >> $GITHUB_OUTPUT

      - name: Install bun
        uses: bun/action-setup@v4
        with:
          version: ${{ steps.bun-version.outputs.bun_version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "bun"

      - name: Install dependencies
        run: bun install

      - name: Create release pull request or publish
        uses: changesets/action@v1
        with:
          publish: bun release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}